import Head from "next/head";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { BarChart } from "../components/BarChart";
import { useTrackItemContext } from "../contexts/trackItemProvider";
export default function Home() {
  const [trackItemList, insertTrackItem] = useTrackItemContext();
  console.l;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header header="Analyze"></Header>
      <BarChart ui={trackItemList} />
      <Footer></Footer>
    </>
  );
}
