import Head from "next/head";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { BarChart } from "../components/BarChart";

export default function Home() {
  const myData = [
    {
      label: "Apples",
      value: 10,
    },
    {
      label: "Oranges",
      value: 17,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header header="Analyze"></Header>
      <BarChart ui={myData} />
      <Footer></Footer>
    </>
  );
}
