import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { useWorkItemContext } from "../contexts/workItemProvider";

export default function Add() {
  const [workItemList, insertWorkItem] = useWorkItemContext();

  const renderedWorkItemList = workItemList.map(() => {});

  return (
    <>
      <Head>
        <title>Track</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header header="Track work"></Header>

      <Footer></Footer>
    </>
  );
}
