import Head from "next/head";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { WorkItemList } from "../components/WorkItemList";

export default function Add() {
  return (
    <>
      <Head>
        <title>Track</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header header="Track work"></Header>
      <WorkItemList />
      <Footer></Footer>
    </>
  );
}
